style:
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false

naming:
  FunctionNaming:
    excludes:
      - '**/MainViewController.kt'
    ignoreAnnotated:
      - Composable
  MatchingDeclarationName:
    active: false
